### ISSUE TITLE
port polymer-ui-toolbar

### ISSUE THREAD

**Issue by ErikGrimes** [bwu-dart-graveyard/polymer_ui_elements#14]
Port polymer-toolbar (https://github.com/Polymer/polymer-ui-elements/tree/master/polymer-ui-toolbar).

**Comment by zoechi** [comment]
ported but has some issues
- [ ] import of polymer_flex_layout in polymer_ui_toolbar.html
- [ ] stylesheet link in polymer_ui_toolbar.html
- [ ] depends on polymer_flex_layout which has issues
- [ ] depends on polymer-media-query which is not yet ported ErikGrimes/polymer_elements#60
- [ ] depends on import from another package #42
