### ISSUE TITLE
polymer-ui-clock doesn't work in Firefox

### ISSUE THREAD

**Issue by beatgammit** [bwu-dart-graveyard/polymer_ui_elements#163]
[Screenshot](http://imgur.com/KtEp9MU).

Also, the month is off by one, as you can probably tell from the screenshot.

**Comment by zoechi** [comment]
Thanks for the report. 
I just tried it in Chrome 33 and it works fine but in Firefox I get the same result as in your screenshot.  
I guess there isn't much I can do besides waiting for an improved polyfill.
Which browser did you use?

**Comment by chankh** [comment]
I think the issue is related to CSS. Look into the file lib/polymer_ui_clock/polymer_ui_clock.html, the styles are -webkit-transform. So it only works in Chrome.

**Comment by zoechi** [comment]
Thanks for the hint. Then it's probably the same problem with JavaScript polymer elements.

**Comment by beatgammit** [comment]
I looked through the code and it's really inconsistent. In some places, it just has webkit prefixes, in others it accounts for `-moz-` and I saw a couple places where it does `-ms-`.

These should all probably be updated to include all vendor prefixes (`-ms-`, `-o-`, `-moz-` and `-webkit-`) as well as their unprefixed version (which I didn't see anywhere).

**Comment by zoechi** [comment]
We do mostly a 1:1 port from the JavaScript Polymer elements. But I'll take a look. Maybe I forgot to update something.

**Comment by beatgammit** [comment]
Upstream is broken too. Perhaps when this is fixed, be a good citizen and push a patch upstream as well?

**Comment by beatgammit** [comment]
I reported this [upstream](https://github.com/PolymerLabs/polymer-ui-elements/issues/34). Their clock demo is broken as well.

**Comment by zoechi** [comment]
thanks a lot!
