### ISSUE TITLE
Polymer_ui_elements 0.2.0-pre.5 does not work with latest dart Dart (SDK version 1.4.0-dev.5.1)

### ISSUE THREAD

**Issue by AnjaGer** [bwu-dart-graveyard/polymer_ui_elements#168]
Hi,

Polymer_ui_elements 0.2.0-pre.5 does not work with latest dart Dart (SDK version 1.4.0-dev.5.1).

When I run the example provided by polymer_ui_elements0.2.0-pre.5 (url http://127.0.0.1:3030/polymer_ui_elements-0.2.0-pre.5/example/index.html, click on polymer_ui_icons) , I get the following error message:

Internal error: 'package:polymer_ui_elements/polymer_ui_iconset/polymer_ui_iconset.dart': error: line 132 pos 3: method 'baseUri' of class 'PolymerUiIconset' conflicts with getter 'baseUri' of super class 'Node'
  String baseUri() {
  ^ 

With Dart SDK version 1.4.0-dev.2.2 it worked fine.
Where has this issue to be fixed? In Dart or in polymer_ui_elements?

Best regards  Anja

**Comment by zoechi** [comment]
Thanks a lot for the report!
I guess we should fix this in polymer_ui_elements. I'll know more after I tracked it down.
Seems there was a feature added I was already waiting for.

**Comment by zoechi** [comment]
I published 0.2.0-pre.6.
Thanks again for the report!

**Comment by AnjaGer** [comment]
When will polymer_ui_elements 0.2.0-pre.6 be available?

**Comment by zoechi** [comment]
Sorry for that! 
When I closed the issue I thought I had published it but obviously I forgot some step :(
I just published 0.2.0-pre.7 and it is already available at pub.dartlang.org.
Please let me know if something doesn't work.
