### ISSUE TITLE
port polymer-ui-tabs

### ISSUE THREAD

**Issue by ErikGrimes** [bwu-dart-graveyard/polymer_ui_elements#40]
Port [polymer-ui-tabs](https://github.com/Polymer/polymer-ui-elements/tree/master/polymer-ui-tabs).

**Comment by zoechi** [comment]
blocked by 
- ErikGrimes/polymer_elements polymer-selector
- ErikGrimes/polymer_elements#29 polymer-flex-layout

**Comment by ErikGrimes** [comment]
What's issue with polymer-selector that's blocking this?

**Comment by zoechi** [comment]
Hi Erik,

the selector element doesn't render properly. But I don't think it's a bug
in polymer-selector itself as it is working well in the selector example.
I guess it has something to do with custom elements importing custom
element from another package not working properly.
I didn't want it to look as if it was your fault but was to tired to
explorate more.

The main task I will focus on now is to track down the causes of the
problems and ask in the forum or file a bug for missing or faulty dart
functionality.

Günter

Mit freundlichen Grüßen

Günter Zöchbauer
guenter@gzoechbauer.com
+43 (699) 10 18 87 15

**Comment by ErikGrimes** [comment]
Yea.  I was just looking to see if I could help!  I took a quick look and
I'm able to get it rendering by giving it corresponding
polymer_ui_tabs.dart file where PolymerUiTabs extends from PolymerSelector.
 Doing this I'm able to see that PolymerSelector.ready is fired, so it's
processing the element at least.  However, selectedChanged is not being
fired.  This leads me to believe that polymer is not properly binding
published attributes of parent elements.

Erik
