### ISSUE TITLE
using polymer_ui_elements with dart sdk 1.0?

### ISSUE THREAD

**Issue by cyrillzadra** [bwu-dart-graveyard/polymer_ui_elements#57]
Is there a way to use this library with dart sdk 1.0?

**Comment by zoechi** [comment]
Hi cyrillzadra,

thank you very much for your interest in polymer_ui_elements.

We have postponed publishing an updated package until a few Dart bugs are fixed
so we can remove some ugly workarounds and are able to build the elements to JavaScript.
The bugs are already fixed but the Dart release containing the fixes is not released yet.
In a few days we should be able to publish a new release to pub.dartlang.org.

In the meantime you can use the elements from the repositories using a path or git dependency.

Path dependecy example:
Check out the polymer_ui_elements and the polymer_elements repository to you local drive
and use a path dependency in your apps pubspec.yaml like:

dependencies:
  polymer_ui_elements:
    path: ../polymer_ui_elements

the polymer_elements dependency in the polymer_ui_elements package should be changed to

dependencies:
  polymer_elements:
    path: ../polymer_elements

(assuming your app and the checkout directories have the same parent directory).

Hope this helps.

Günter

**Comment by cyrillzadra** [comment]
Thanks for detailed explanation. I started copying the components in my project.. but your way is much better :)
