### ISSUE TITLE
Fix authors in pubspec.yaml

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_ui_elements#9]

**Comment by ErikGrimes** [comment]
What's the issue exactly?

**Comment by zoechi** [comment]
On 11/01/2013 04:28 PM, ErikGrimes wrote:

> What's the issue exactly?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ErikGrimes/polymer_ui_elements/issues/9#issuecomment-27573755.
> 
> I would like to have the names/email adresses like in the authors file
> as all or most other packages have them.
> This was meant as an issue I created for myself as reminder not as a
> task for you to do.

We have to modify the README.md at least for now. If you take a look at
pub.dartlang.org you will know what I mean.
Either we do the table formatting in some other way or move the table to
another page and create a link in README.md.
I filed a bug for the missing support of HTML tags on pub.dartlang.org.

Today is a public holiday in Austria and I had some private obligations
and could not go on fixing those yet.

Do you know where the source for this page
http://www.polymer-project.org/docs/elements/ can be found?
I would like to have the same as github page for our project.
Otherwise I post a question on their discussion group.

Günter

**Comment by ErikGrimes** [comment]
On Fri, Nov 1, 2013 at 1:15 PM, Günter Zöchbauer
notifications@github.comwrote:

> On 11/01/2013 04:28 PM, ErikGrimes wrote:
> 
> > What's the issue exactly?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ErikGrimes/polymer_ui_elements/issues/9#issuecomment-27573755
> > .
> > 
> > I would like to have the names/email adresses like in the authors file
> > as all or most other packages have them.
> > This was meant as an issue I created for myself as reminder not as a
> > task for you to do.

Ahh.  I review everything that hits the issues list.  It's probably good in
this case.  See my PM.

> We have to modify the README.md at least for now. If you take a look at
> pub.dartlang.org you will know what I mean.

Either we do the table formatting in some other way or move the table to

> another page and create a link in README.md.

I saw.  Someone submitted a pull request with a markdown formatted table.
 Is pub.dartlang.org  just displaying the README? If so, we could ask in
misc if markdown tables are supported.

> I filed a bug for the missing support of HTML tags on pub.dartlang.org
> 
> Today is a public holiday in Austria and I had some private obligations
> and could not go on fixing those yet.

Woo!  I hope you enjoyed your holiday.
